# Generated by Django 2.0.5 on 2018-08-14 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0003_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='message',
        ),
    ]
