# Generated by Django 2.0.5 on 2018-08-14 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0004_remove_comment_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='message',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
