# Generated by Django 2.0.5 on 2018-08-14 04:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0005_comment_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 14, 0, 54, 25, 680727)),
        ),
    ]
